### ISSUE TITLE
Missing an example for using waitUntil() for metrics

### ISSUE THREAD

**Issue by arturenault** [vercel/examples#164]
I'm trying to set up datadog tracing in my NextJS app. It seems like this should be possible with middleware, but I'm not finding an example for this.

The docs say: [```An example of why you would use waitUntil() is integrations with logging tools such as [Sentry](https://sentry.io/) or [DataDog](https://www.datadoghq.com/). After the response has been sent, you can send logs of response times, errors, API call durations or overall performance metrics.```](https://nextjs.org/docs/api-reference/next/server#nextfetchevent)

But I'm not finding a way of executing code in the middleware after the response has been returned to the caller, and I'm finding several folks confused by similar use cases:
- https://github.com/vercel/next.js/discussions/34436
- https://github.com/vercel/next.js/discussions/33893
- https://github.com/vercel/next.js/discussions/34420

Can we get an example of this?

**Comment by lfades** [comment]
Hi @arturenault I hope you're doing well!

We have not decided yet about the best place to send analytics and middleware has some constraints around it, I'll come back to you in the future but for the moment I'll close the issue as analytics and logging won't be added using edge functions in our examples.

**Comment by arturenault** [comment]
Thanks, I'll look forward to that! We should probably change the docs then, at least, as it specifically mentions this as a use case for middleware.

**Comment by lfades** [comment]
@arturenault I opened a PR for that in the Next.js repo: https://github.com/vercel/next.js/pull/35622 (it's merged)

**Comment by Noitidart** [comment]
Aw dang, was looking for a place to do this. Looking forward to see when a solution is given for analytics like datadog.

**Comment by Noitidart** [comment]
Does anyone else have any example of middleware where they do code before the api-route runs and then after the api-route finishes running?

**Comment by mquandalle** [comment]
Also curious what is the recommended solution to insert a record in a database for analytics without blocking the HTTP response. I tried log drains but it's really a mess to retrieve a simple Json object.

**Comment by Noitidart** [comment]
@mquandalle it seems we can run dd-trace as discovered here - https://github.com/vercel/next.js/discussions/16600 - it links to - https://jake.tl/notes/2021-04-04-nextjs-preload-hack
