### ISSUE TITLE
Server side analytics

### ISSUE THREAD

**Issue by carlosagsmendes** [vercel/examples#19]
Hi, can you point me to the server-side analytics example?

Thanks in advance

**Comment by fredericrous** [comment]
I tried to use firebase to do serverside analytics but I didn't succeed.
Here's my code: (of course we can't use firebase-admin because it depends on fs module)

```
import type { NextFetchEvent, NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import db from '@/lib/firebase';
import { ref, runTransaction } from 'firebase/database';

const logView = async (slug) => {
  const { snapshot } = await runTransaction(ref(db, 'views/' + slug), (currentViews) =>
    currentViews === null ? 1 : currentViews + 1
  );
  return snapshot.val();
};

export function middleware(req: NextRequest, ev: NextFetchEvent) {
  const { pathname } = req.nextUrl;
  if (!/^\/static/.test(pathname)) {
    const noSlashPathName = pathname.replace(/^\//, '').replace(/\//g, '-');
    logView(noSlashPathName).catch(console.log);
  }

  return NextResponse.next();
}
```

if I `await` the function `logView`, the request hangs forever

there is no error logged in the console

**Comment by leerob** [comment]
I have a WIP version going here for Next.js https://github.com/leerob/leerob.io/pull/431

**Comment by gbibeaul** [comment]
👋 I'll take this over and add to @leerob's example making a more complete on in this repo! Should get releasd within 5-10 adys

**Comment by gbibeaul** [comment]
Closing this as we merged the example:

Code: https://github.com/vercel/examples/tree/main/edge-functions/analytics
Deployed explainer: https://edge-functions-analytics.vercel.app/
