### ISSUE TITLE
JWT Auth example

### ISSUE THREAD

**Issue by davodesign84** [vercel/examples#21]
when implementing the jwt auth example in my app i get the following in the verce dev logs: `'eval' not allowed in Middleware pages/_middleware`

This does not seem to happen with the example itself but the error message is not particularly clear about what is causing the issue. Any pointers?

**Comment by lfades** [comment]
The package is currently using https://www.npmjs.com/package/jose, if there are any issues with the current example please let us know and sorry for the late response!

**Comment by davodesign84** [comment]
Hi @lfades  thank you for responding :) I did figure it out eventually :D
