### ISSUE TITLE
There is not much documentation about with javasccript for middleare edge nextjs 12 

### ISSUE THREAD

**Issue by ats1999** [vercel/examples#23]

**Comment by sadiquekp** [comment]
correct, how can I set middleware for specific routes only ?

**Comment by mmmeff** [comment]
Yeah, having a hard time figuring out how these are supposed to be used as well. 

Can't reason about how to add a header to a page response. The example has a completely empty response being returned. Instead, I want to add a header to every page's response...

**Comment by leerob** [comment]
Are you saying you want plain JavaScript and not TypeScript? 

> Can't reason about how to add a header to a page response. 

Did you see this? You can return right here with the `null` to just add headers to the response: https://github.com/vercel/examples/blob/main/edge-functions/add-header/pages/_middleware.ts#L13

**Comment by nyg** [comment]
@mmmeff You can do it like this:

```js
import { NextResponse } from "next/server"

export default function myMiddleware(req) {
  const res = NextResponse.next()
  res.headers.append('x-custom-1', 'ok')
  return res
}
```

`.next()` adds a custom header to the response which will ensure it is not returned immediately to the client (but pages/api will be executed).

**Comment by ali-alhussain** [comment]
@leerob For me, yes I want to know if I can use Javascript instead of Typescript?

And is there any examples for it?

**Comment by leerob** [comment]
Yes, you can use JavaScript instead of TypeScript. TS is a superset of JS, so you can just remove the typings and TS specific code on any example.

**Comment by leerob** [comment]
We will be continuing to make examples in TypeScript, since you can remove the typings to get JavaScript, versus the inverse where you might not understand how to correctly type the code.

**Comment by ali-alhussain** [comment]
@leerob thanks for your quick reply!
