### ISSUE TITLE
Same item showing up multiple times on main page

### ISSUE THREAD

**Issue by garciagomezluis** [vercel/examples#237]
Searching for an example, I'm getting an extra item:

Example: "API Rate Limit"

![image](https://user-images.githubusercontent.com/3448431/164915497-9e76d5be-c9cb-47f7-b76e-4b7486aabd04.png)

Another item, example: "tweet"

![image](https://user-images.githubusercontent.com/3448431/164915563-ebbc58c2-ed54-4aaa-853d-f543f3ba9999.png)

And so on...

I couldn't find where this list is being rendered to try to detect the problem, but inspecting with the react dev tools I noticed that only the "tweet" item is present.

![image](https://user-images.githubusercontent.com/3448431/164915889-5674d4c4-80db-4151-a09d-2a0a90e52b61.png)

On Chrome Version 99.0.4844.51 (Official Build) (64-bit) - Ubuntu 20.04 LTS

Not sure if this is the correct place to report the issue. Please let me know.

**Comment by garciagomezluis** [comment]
@goncy

**Comment by lfades** [comment]
👋 

The site shown in the issue is an experimental project we worked on but it's never going to launch, the official place for our examples is [vercel.com/templates](https://vercel.com/templates).
