### ISSUE TITLE
i18n with Next.js' built-in i18n?

### ISSUE THREAD

**Issue by KATT** [vercel/examples#28]
The edge-function [example using i18n](https://github.com/vercel/examples/tree/main/edge-functions/i18n) is not using the normal [Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing) but rather a custom file route-based approach.

Will edge functions support "proper" i18n? If so, is there a timeline?

I'm evaluating if it's worth rewriting everything using this EF approach and essentially moving all of the `pages/*` to `pages/[locale]/*`.

**Comment by lfades** [comment]
The example is about showing that it's possible to do i18n without using the Internationalized Routing feature of Next.js for the cases where it's lacking features required for your use case or other edge cases.

> Will edge functions support "proper" i18n? If so, is there a timeline?

There's no timeline for it and I would not expect it soon, as you can run any custom code you want in _middleware there's a lesser need for abstractions.
