### ISSUE TITLE
Cannot deploy "Basic Auth Password Protection" example to Vercel

### ISSUE THREAD

**Issue by judewang** [vercel/examples#32]
### Problem

I copied and pasted the `_middleware.ts` from example repo to my Next project, everything worked fine on development environment, and I can run `yarn build` successfully. When trying to deploy to Vercel, I kept getting an error said `An unexpected internal error occurred`, then the deploy got failed. The error happened right after `Uploading build outputs...`.

I found the [official example](https://github.com/vercel/examples/tree/main/edge-functions/basic-auth-password) will meet the error, too. We cannot even deploy the official example to Vercel.

### How to re-produce the issue

Just click the `Deploy` button on the [README](https://github.com/vercel/examples/tree/main/edge-functions/basic-auth-password) page.

![CleanShot 2021-11-04 at 18 27 28](https://user-images.githubusercontent.com/1559819/140289902-166c77f1-c10d-4d06-8c6b-6bd2730ee0de.png)

![CleanShot 2021-11-04 at 18 34 47](https://user-images.githubusercontent.com/1559819/140290811-e3287a88-1e2f-4731-9bda-d7a981d1e13b.png)

**Comment by juanantona** [comment]
I was having a similar issue a few hours ago and finally, I was able to deploy it

**Comment by judewang** [comment]
It worked now, thanks.
