### ISSUE TITLE
Other language example

### ISSUE THREAD

**Issue by Himself65** [vercel/examples#373]
I'm looking for the python example from https://vercel.com/docs/runtimes, which I can `git clone` and run the code

**Comment by leerob** [comment]
-   We now have a deployable example with a [hello world API ](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e)([demo](https://python-hello-world.vercel.app/api))
-   We now have a deployable example with [Flask](https://github.com/vercel/examples/tree/main/python/flask) ([demo](https://flask-python-template.vercel.app/))
-   We now have a deployable example with [Django](https://github.com/vercel/examples/tree/main/python/django) ([demo](https://django-template.vercel.app/))
