### ISSUE TITLE
The fallback value used in the Prerender Functions does not match the specification

### ISSUE THREAD

**Issue by morinokami** [vercel/examples#400]
According to [the Build Output API specification](https://vercel.com/docs/build-output-api/v3#vercel-primitives/prerender-functions/configuration), the value of `fallback` in `.vercel/output/functions/<name>.prerender-config.json` should be a string. However, the `fallback` value used in https://github.com/vercel/examples/blob/main/build-output-api/prerender-functions/.vercel/output/functions/blog/post.prerender-config.json is not a string but an object, so it needs to be modified to match the specification.

I think we can simply change the `fallback` value from the object to the value of `fsPath` in the object (that is, `"fallback": "post.prerender-fallback.html"`). I made the change locally and deployed it via the `vercel deploy --prebuilt` command, and it seems to work without a problem.

**Comment by lfades** [comment]
cc @TooTallNate @styfle

**Comment by TooTallNate** [comment]
Thanks for the report. Fixed!
