### ISSUE TITLE
Prop href did not match. Server & Client

### ISSUE THREAD

**Issue by Manikanta-20** [vercel/examples#41]
@lfades 

### Developed Custom  middleware based on cookies

Passing data from one page to another page using router.push.When  accessing using useRouter() in another page.

Getting below message in browser console

> Prop href did not match. Server: "/second#" Client: "/second?id=45&
name=sai&buildingName=ss&no=&street=555555#"

**_Below code of middleware function_**

```
import { NextResponse } from 'next/server';

function middleware(request) {
  const cookie = request.cookies.token;
  const { pathname } = request.nextUrl;
  if (
    cookie === undefined &&
    ['/first','/second'].includes(pathname)
  ) {
    return NextResponse.redirect('/login');
  }


  if (
    cookie !== undefined &&
    ['/sample' ].includes(pathname)
  ) {
  return NextResponse.next();
}
return NextResponse.next();
}


export default middleware;


```

How fix above issue?

**Comment by lfades** [comment]
Hi @Manikanta-20 and sorry for the late response!

Your code looks good and unrelated to the error you're getting, I'm going to close the issue because it's been a while and hopefully you have sorted it out, otherwise let me know and I'll re-open it!
