### ISSUE TITLE
Dynamic slug is not available under sites

### ISSUE THREAD

**Issue by suresh-kumar-ogilvy** [vercel/examples#427]
Hi 

If we create a file under _sites/[site]/[[...slug]].tsx getting the following error

A required parameter (slug) was not provided as an array in getStaticPaths for /_sites/[site]/[[...slug]]

getStaticPaths passed 

 { params: { slug: '/home', site: 'subdomain-1' } },
  { params: { slug: '/home', site: 'site1' } },
  { params: { slug: '/home', site: 'site2' } }

We are trying to add dynamic routing inside sites, instead of creating home.tsx, about.tsx 

Please advise if is there a way to implement this.

**Comment by lfades** [comment]
Please open an issue with a reproduction in the Next.js repository, that's the right place to address bugs with Next.js 🙏
