### ISSUE TITLE
Query params filter infinite redirect

### ISSUE THREAD

**Issue by ihmpavel** [vercel/examples#45]
Query params filter has infinite redirection loop

Edge function folder: https://github.com/vercel/examples/tree/main/edge-functions/query-params-filter

Bug:
Loading URL from readme - https://edge-functions-query-params-filter.vercel.sh/?a=b&allowed=test leads to an infinite redirection loop

OS: Windows 10, latest Chrome, Edge
![image](https://user-images.githubusercontent.com/42217494/141869322-bc5d7813-17c0-4b41-89e2-cf72364fccb9.png)

**Comment by ardaerzin** [comment]
we were planning on building a middleware with this functionality, but we are blocked by this issue. on local it works as expected/advertised

**Comment by javivelasco** [comment]
Just a heads up we are discussing what the solution for this would be, we are shipping a solution soon.

**Comment by Schniz** [comment]
Hey @alexliebler! We fixed the issue:

* https://github.com/vercel/examples/pull/117
* https://github.com/vercel/next.js/pull/33725
 
new deployments that delete query params (like our example) will work too

**Comment by leerob** [comment]
Thank you @Schniz ❤️
