### ISSUE TITLE
I can have multiple custom domains using host-rewrites, correct?

### ISSUE THREAD

**Issue by JohnAllen** [vercel/examples#49]
Just want to make sure. There is an emphasis on sub-domains in the docs and example. And I do see multiple custom domains. But there is a single root domain in the `.env` file, and I don't really want a root domain, I just want multiple root/main/host names that are related, but different.

**Comment by JohnAllen** [comment]
There's also this line in the README:

> Do note that you will need to replace the ROOT_URL variable in the .env.example file with your domain of choice and add that domain as a wildcard domain your Vercel project.

**Comment by steven-tey** [comment]
Hey @JohnAllen! Steven here, creator of the hostname rewrites example! What do you mean by "I just want multiple root/main/host names that are related, but different"? 

To clarify, the `ROOT_URL` is basically the URL that you want to use for all your subdomains. For example, take Substack as an example – `substack.com` is the `ROOT_URL` and that will be used for all the subdomains that users get (`steven.substack.com`, `john.substack.com`)

**Comment by JohnAllen** [comment]
Thanks for the response @steven-tey! 

I want to have multiple domains/hostnames use the same codebase, essentially. Similar sites sharing code but are different, mostly for geographic & SEO purposes. So I do not want many subdomains. I want many hostnames. I am wondering if this host-rewrites approach is the best way to do it and what alternatives there are.

I get the "platform" example like Substack. Instead I want to have many hostnames and not subdomains. I know I can sort of hack the i18n feature of Next/Vercel, just wondering the other ways to accomplish my goal before I write much code :)

**Comment by JohnAllen** [comment]
I mostly figured it out. Still trying to figure out how to dev with multiple sites on localhost using getStaticProps and getStaticPaths

**Comment by moinulmoin** [comment]
@JohnAllen Hi, I am stuck with something. I have created an issue on it. Could you please take a look? thanks

**Comment by webberwang** [comment]
For `[custom-domain-1.com](https://custom-domain-1.com/) (custom domain, maps to [subdomain-1.vercel.sh](https://subdomain-1.vercel.sh/))`

What does the owner of `https://custom-domain-1.com/` have to change in terms of DNS records to point to `subdomain-1.vercel.sh`?
