### ISSUE TITLE
`_middleware.js` example without Next.js

### ISSUE THREAD

**Issue by remorses** [vercel/examples#50]
Is there an example of using `_middlware.js` wihout Nextjs?

My use case is to use `_middlware.js` as a reverse proxy, the problem of using nextjs is that `_middlware.js` won't reroute anything with path starting with `/_next`

**Comment by leerob** [comment]
Hey! We’re working on adding some examples for this. Middleware does indeed work with any framework, or just vanilla HTML, by placing the _middleware file in your root directly (or for framework authors, using the [File System API](https://vercel.com/docs/file-system-api)).

**Comment by brycewray** [comment]
Am I correct in assuming this is unlikely to be addressed until 1Q 2022 due to the upcoming year-end holidays? Just curious. TIA for any such info.

**Comment by ptrhck** [comment]
Any news on this topic?

**Comment by remorses** [comment]
For anyone trying to use `_middleware.js` without next i am going to list some findings that may be useful:
- you must have a `package.json` file on root too or it won't work.
- Another cool thing to know is that you can also use `_middleware.ts` (using typescript) without any configuration because vercel bundles the _middleware file with esbuild on deployment
- if you are trying to use `NextResponse.rewrite` from nextjs, you can use the following function for the same result
```js
function rewrite(destination) {
    return new Response(null, {
        headers: {
            'x-middleware-rewrite':
                typeof destination === 'string'
                    ? destination
                    : destination.toString(),
        },
    })
}
```
- For other cases just replace `NextResponse` with `Response`
- To get `req.nextUrl.pathname` you can do `new URL(req.url).pathname`

**Comment by brycewray** [comment]
@remorses Although this doesn't eliminate the need for non-Next documentation from Vercel, it nonetheless is interesting and useful. Thanks!

**Comment by leerob** [comment]
We're still working on it - apologies for the delay.

**Comment by brycewray** [comment]
@remorses Just as a starter for those of us not all that into Next 😄 , how would you adjust the following `_middleware.ts` code from the fairly simple example, https://github.com/vercel/examples/tree/main/edge-functions/add-header ? In particular, the part of **each** of the examples that throws me is always the `import` statement in the top part, since that statement and the subsequent use of `NextRequest` both obviously depend on Next. To a Next-savvy person, a non-Next substitution probably seems super-easy, but a non-Next-savvy guy like me wouldn't have a clue where to go from there. Thanks in advance for any related thoughts you might have.

```js
import type { NextRequest } from 'next/server'

export function middleware(req: NextRequest) {
  // You can add and append headers in multiple ways,
  // below we'll explore some common patterns

  // 1. Add a header to the `Headers` interface
  // https://developer.mozilla.org/en-US/docs/Web/API/Headers
  const headers = new Headers({ 'x-custom-1': 'value-1' })
  headers.set('x-custom-2', 'value-2')

  // 2. Add existing headers to a new `Response`
  const res = new Response(null, { headers })

  // 3. Add a header to an existing response
  res.headers.set('x-custom-3', 'value-3')

  // 4. Merge existing headers with new ones in a response
  return new Response(
    'Open the network tab in devtools to see the response headers',
    {
      headers: {
        ...Object.fromEntries(res.headers),
        'x-custom-4': 'value-4',
      },
    }
  )
}
```

**Comment by remorses** [comment]
Instead of NextRequest you have to use Request, which is a [javascript built in](https://developer.mozilla.org/en-US/docs/Web/API/Request)

To migrate to a simple request, you can see how `NextRequest` is implemented [here](https://github.com/vercel/next.js/blob/c497b3a5ff3199967f476323b9d2287f97ecbdea/packages/next/server/web/spec-extension/request.ts)

**Comment by ptrhck** [comment]
@brycewray Would be great if you can share your code once implemented!

**Comment by brycewray** [comment]
@ptrhck I haven't yet been able to make anything (i.e., that works). While @remorses provided valuable info, there are just too many other items that I'm not savvy enough to "translate" from Next to non-Next. Sorry!

**Comment by dapptain** [comment]
Any update on documentaion for non-nextjs projects. All the above is helpful, but something a bit more formal would be much appreciated.

**Comment by frandiox** [comment]
Alright, looks like it works when using `middleware-manifest.json` instead of `functions-manifest.json`, which is what `next build creates.

**Comment by frandiox** [comment]
For anyone interested, I've made an example on how to deploy to Vercel Edge without Next.js: https://github.com/frandiox/hydrogen-vercel-edge
Demo: https://hydrogen-vercel-edge-frandiox.vercel.app/

As mentioned before, the key was using `middleware-manifest.json` instead of `functions-manifest.json`.
cc @leerob Perhaps this could be updated in the docs?

**Comment by brycewray** [comment]
> For anyone interested, I've made an example on how to deploy to Vercel Edge without Next.js: https://github.com/frandiox/hydrogen-vercel-edge

Nice!

(But requires Shopify, right? I think what most of us are seeking are examples that require **no** specific platform but, rather, are as vanilla as possible.)

**Comment by edcrampin** [comment]
> For anyone interested, I've made an example on how to deploy to Vercel Edge without Next.js: https://github.com/frandiox/hydrogen-vercel-edge Demo: https://hydrogen-vercel-edge-frandiox.vercel.app/
> 
> As mentioned before, the key was using `middleware-manifest.json` instead of `functions-manifest.json`. cc @leerob Perhaps this could be updated in the docs?

Thanks @frandiox, nice example using the File System API - that raises a good point that there are really two parts to this issue, I think what we need in this repo is an example of both:
- Middleware using the [File System API](https://vercel.com/docs/file-system-api#resources/middleware)
- Middleware with just a simple `_middleware.js`, with no need to play with the File System API

It seems like the second point is supported in Vercel, but perhaps not fully working/documented yet. As @brycewray mentions, I think this is what most people would be seeking so that the overhead of setting up Vercel middleware for a non-Nextjs project is as simple as possible.

**Comment by leerob** [comment]
I see you mentioned Hydrogen - what other frameworks are y'all wanting to use Middleware with? P.S. I'm still following along here 😄

**Comment by brycewray** [comment]
> I see you mentioned Hydrogen - what other frameworks are y'all wanting to use Middleware with? P.S. I'm still following along here 😄

Can’t answer for others, @leerob, but I just want as plain-vanilla JS as possible, for converting an existing CF Worker to work on Vercel. Since Edge already uses CF Workers, seems it wouldn’t be that hard, although I readily confess that I’m only guessing about that.

**Comment by david-morris** [comment]
@leerob I'm using docusaurus, so I think that means static HTML.

**Comment by david-morris** [comment]
@edcrampin could you share the repo you have for converting the basic password auth? That would be a great example to work from.  I'm having trouble understanding the various roots in the project, i.e., where the middleware should go.

**Comment by dapptain** [comment]
HELP! WE NEED DOCUMENTATION. ffs.....

**Comment by brycewray** [comment]
With the understanding that there may not be bandwidth at Vercel to reproduce all the examples in non-Next form, maybe @leerob *et al.* could take just **one** of the simpler examples — such as [add-header](https://github.com/vercel/examples/tree/main/edge-functions/add-header) or [geolocation](https://github.com/vercel/examples/tree/main/edge-functions/geolocation) — and produce a non-Next form of it. It would be like a [Rosetta Stone](https://en.wikipedia.org/wiki/Rosetta_Stone), showing that “Thing A gets done in Next projects like **this** (existing example) but in plain-vanilla JS it gets done like **this** (proposed example).” That could be really helpful and, perhaps, wouldn’t take too much time to convert from whichever Next project you select.

Just a thought. 🙂

**Comment by edcrampin** [comment]
@brycewray agreed, I've been planning to raise a PR to add something like this for a few basic examples using both the file system API and potentially also fully vanilla (single middleware file?) but struggling to get the time to look at this for now. The main nuisance to work around is how to organise middleware examples in this repo, and then also re-working the plop scripts to support this new structure. 

I'd propose `edge-functions` would consist of three subdirectories, something like:
- `nextjs`
- `vanilla`
- `filesystem-api`

...and moving all existing examples to the `nextjs` dir and starting to recreate some of the existing Next.js examples in the other subdirectories.

**Comment by brycewray** [comment]
@edcrampin That all sounds great! It’ll be tremendously appreciated — **but** I humbly re-suggest :) that, in the meantime and in view of the team’s absolutely understandable time limitations, the starting effort be something utterly simple, quick, and dirty, even if it’s only a vanilla version of `middleware.js` for a given example but with everything else in that example left as-is.

**Comment by edcrampin** [comment]
@brycewray sounds completely sensible - I'll see what I can do.

**Comment by edcrampin** [comment]
@brycewray [here's an example](https://github.com/edcrampin/vercel-examples/tree/feature/extended-examples/edge-functions/create-react-app) of an `add-header` and `basic-auth` middleware using `create-react-app`. The `_middleware.ts` file is compiled by ESBuild at build time within Vercel so having TypeScript does not matter despite being a non-TS project. These two examples are currently deployed here:
- [add-header](https://add-header-cra-edcrampin.vercel.app/)
- [basic-auth](https://basic-auth-cra-edcrampin.vercel.app/)

These mostly work but I'm coming across the same issue as I mentioned previously where certain assets return a 404 which I believe to be a bug within Vercel somewhere as certain assets load fine whilst others don't. Here's an example from the `add-header` example I included, you can see the custom headers in the response headers but the `main.XXXX.js/css` files are returning 404 so the React app does not load. @leerob is this something you're aware of at all?

<img width="714" alt="image" src="https://user-images.githubusercontent.com/6486622/159055169-2a3bae0a-8981-4c13-a2a5-37b8d4bff176.png">

**Comment by brycewray** [comment]
@edcrampin Thanks very much! Will stand by for @leerob to weigh in on your question before trying.

**Comment by brycewray** [comment]
@edcrampin At the risk of being a real pest, I wonder: must it be a TypeScript file? I hadn’t noticed until now that all the Edge Functions examples — including yours — are TypeScript. Wasn’t aware that mattered.

**Comment by david-morris** [comment]
Thanks for the example, @edcrampin ! I feel that I've been able to rule out issues with the _middleware file and package.json thanks to that repo.

However, there appears to be some remaining issue, and I don't understand where to start analyzing this issue.  It appears that moving the _middleware file will switch this error between being a simple middleware and a filesystem API issue, but there's something that the edge function deployer just doesn't like about ...something? My repo?  My framework? My account?

As an aside, it would be nice to be able to test these things without waiting for a remote deployment and committing.

I'd love to hear input on what could be related to this issue, and I'm interested in helping to make sure that the documentation can help people who are using whatever new technology, and want to add middleware.
```
TypeError: Unexpected MODIFIER at 1, expected END
    at parse (/vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:1:539986)
    at stringToRegexp (/vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:1:542405)
    at Object.pathToRegexp (/vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:1:543583)
    at sourceToRegex (/vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:1:224129)
    at /vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:1:222434
    at Array.map (<anonymous>)
    at convertRedirects (/vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:1:222402)
    at Object.build (/vercel/b8b564fa9bd13b57/.build-utils/.builder/node_modules/@vercelruntimes/file-system-api/dist/index.js:31:90032)
    at async qot (/var/task/sandbox.js:197:12762)
```

**Comment by charlax** [comment]
I'm also using the latest docusaurus and getting the same error `TypeError: Unexpected MODIFIER at 1, expected END`.

**Comment by david-morris** [comment]
@edcrampin , could you share more about the settings you're using to deploy your example?  

I assumed that it would use either the Other or Create React App preset, with the root directory `edge-functions/create-react-app/basic-auth` (for the basic auth example), and no other settings changed.

I've tried deploying it and it failed:
```
Cloning bitbucket.org/Nefino/vercel-examples (Branch: main, Commit: 540430d)
Cloning completed: 1.921s
Installing build runtime...
Build runtime installed: 4.358s
Looking up build cache...
Build Cache not found
Detected package.json
Installing dependencies...
Detected `package-lock.json` generated by npm 7...
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
added 1369 packages in 45s
169 packages are looking for funding
  run `npm fund` for details
Running `vercel build`
Vercel CLI 23.1.3-canary.71 build (beta) — https://vercel.com/feedback
Retrieved Project Settings:
  - Framework Preset: Create React App
  - Build Command: `npm run build` or `react-scripts build`
  - Output Directory: build
Loaded 2 CLI Plugins
Running Build Command: `npm run build`
> basic-auth@0.1.0 build
> react-scripts build && cp _middleware.ts ./build/
Creating an optimized production build...
Compiled successfully.
File sizes after gzip:
  42.77 kB  build/static/js/main.3dba3da1.js
  541 B     build/static/css/main.073c9b0a.css
The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.
The build folder is ready to be deployed.
You may serve it with a static server:
  npm install -g serve
  serve -s build
Find out more about deployment here:
  https://cra.link/deployment
Copying files from "build" to ".output/static"
Copied 14 files from "build" to ".output/static" [38ms]
Running 2 CLI Plugins after Build Command:
  > vercel-plugin-middleware.build: Compiling middleware file: "/vercel/path0/edge-functions/create-react-app/basic-auth/_middleware.ts"
Build Completed in .output [12s]
Uploading build outputs...
An unexpected internal error occurred
```

**Comment by ptrhck** [comment]
I was also trying to deploy the example and now I am even getting the following:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26689889/161260037-56c14a72-1884-4a5b-a9e8-6f1a2776fbb8.png)
So, I am really wondering what the current status is here?

**Comment by charlax** [comment]
Btw, I got the following response from Vercel support:

> Edge Functions (beta) are not ready outside of Next.js at the moment. We are working on making this possible!

So I guess we just have to be patient :)

**Comment by red2678** [comment]
I feel like you guys putting examples of middleware implementations on your site, saying you work with all sorts of frameworks, only to not, is blatantly false advertising. 

![image](https://user-images.githubusercontent.com/1896036/162613659-8f94abc5-37c1-43ed-b101-26a20ad68b7d.png)

![image](https://user-images.githubusercontent.com/91151091/162613486-a4183de7-06a9-4ad0-88c6-ab86cb5f62b5.png)

Nowhere on these pages does it say that middleware is only supported by Next.js apps. 

https://vercel.com/features/edge-functions

https://vercel.com/docs/concepts/functions/edge-functions

Riiiiiiiight......

![image](https://user-images.githubusercontent.com/1896036/162613704-04787589-8865-40f3-b7c1-adbe4332fff8.png)

**Comment by leerob** [comment]
Forgot to swing back here, but with the stable release of Middleware, it can now be used with all frameworks 😄 

- https://github.com/vercel/examples/pull/320
- https://github.com/vercel/examples/pull/353

https://vercel.com/docs/concepts/functions/edge-middleware/quickstart

**Comment by brycewray** [comment]
I did finally get it working on a Hugo repo:
https://github.com/brycewray/hugo-site/blob/main/middleware.js

While most of its headers-handling could’ve been done in `vercel.json`, the Content Security Policy needed dynamically generated nonces scattered throughout the site at appropriate places (scripts, certain links, etc.). This handles that just as its Cloudflare Worker predecessor did. 👍

**Comment by dmarkbreiter** [comment]
@david-morris @charlax did you ever get your docusaurus sites behind authentication?

**Comment by david-morris** [comment]
@dmarkbreiter yes, I think we just crammed Docusaurus behind a Next.js shim before this was fixed though.

**Comment by Youhan** [comment]
Is there a `Nuxt` example out there?

**Comment by jkmartindale** [comment]
Since this is still the easiest resource to find for using Vercel middleware without Next, here's a tip I wish I had known earlier.

[@vercel/edge](https://www.npmjs.com/package/@vercel/edge) gives you `rewrite()`/`next()` like `NextResponse` but without the headache of loading all of Next just for middleware. This is my simple middleware for disabling direct file access on a project that's just serverless functions, which is another annoying Vercel default but whatever:

```ts
import { rewrite } from "@vercel/edge"

export const config = {
    matcher: "/((?!api|static).*)",
}

export default function middleware(_request: Request) {
    return rewrite("/404")
}

```
