### ISSUE TITLE
Monorepo solution missing "next/babel"

### ISSUE THREAD

**Issue by 0x80** [vercel/examples#500]
When running the monorepo solution eslint complains in the next.config.js file that it can't find "next/babel".

I've read [here](https://stackoverflow.com/questions/68163385/parsing-error-cannot-find-module-next-babel) that you can add a .babelrc file with 

```
{
  "presets": ["next/babel"],
  "plugins": []
}
```

... but then you also need to install an extra dependency so I'm not sure if that is the way to go.

I'm running the example locally using `pnpm create next-app --example https://github.com/vercel/examples/tree/main/solutions/monorepo monorepo`

**Comment by lfades** [comment]
This is an issue with VS Code (as that's where I see this error), not with Next.js, **do NOT add a `.babelrc` to fix this** as [Next.js uses SWC](https://nextjs.org/docs/upgrading#swc-replacing-babel) nowadays.
