### ISSUE TITLE
Cannot add @next/font/google into the ImageResponse

### ISSUE THREAD

**Issue by vladgardus** [vercel/examples#501]
Hello,

I'm trying to import a google font and use it in my image response. The code using is as follows:
const poppins = Poppins({ weight: ["400"], subsets: ["latin"], display: "swap" });
<div tw={`flex flex-row-reverse h-full bg-neutral-800`} className={poppins.className}>Test</div>

The issue is that my font doesn't get used when generating the image.

**Comment by radromanov** [comment]
Hi vladgardus,

Are you still having issues with making the font work? If so, I've got a couple of questions to better understand your issue:
1. Can you share your implementation of the `poppins` variable?
2.  Are you using Tailwind?
    -  if you _are_ using Tailwind, could you show me your `tailwind.config.js` file?

Hope you've managed to sort it out in the meantime!

**Comment by lfades** [comment]
Closing as stale.
