### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by C-EO** [vercel/examples#502]
Do you provide help for setting up the `**[platforms-slate-supabase](https://github.com/vercel/examples/tree/main/solutions/platforms-slate-supabase)**` project?

The tutorial provided [here](https://vercel.com/guides/nextjs-multi-tenant-application) isn't helping me.
It's just confusing me more

Whenever I try to build the site in my Vercel project, it throws out `lint` errors

**Comment by lfades** [comment]
Can you provide more information into what's confusing you? that tutorial is a bit advanced but feedback is welcomed. cc @steven-tey 

I'm to close the issue now as that example doesn't live in this repo, if you find any issues with Next.js itself please report them to the Next.js repository.
