### ISSUE TITLE
Remove template header and footer

### ISSUE THREAD

**Issue by preferium** [vercel/examples#522]
Hi. How do I remove the header and footer from template I have deployed. Can't manage to find where it's located in the files. Please help.

<img width="1415" alt="Skjermbilde 2023-01-19 kl  10 44 15" src="https://user-images.githubusercontent.com/122758653/213409858-e12aa20f-b3d2-4e6f-a5af-d0825241d837.png">

**Comment by dominiksipowicz** [comment]
Closing as this was answered in #521.
