### ISSUE TITLE
Bug: Static Tweet Example Needs Better Null/Undefined Checks

### ISSUE THREAD

**Issue by program247365** [vercel/examples#537]
This is a small bug in the static-tweets-tailwind example. Let me know if you want me to create a PR for this.

Ran into this when firing up the https://github.com/vercel/examples/tree/main/solutions/static-tweets-tailwind example for the first time.

Some of the example tweets have no images in their `url_meta`, so the app throws an error

![Screenshot 2023-01-31 at 10 44 29 AM](https://user-images.githubusercontent.com/13910/215807696-58c88172-b010-4fd4-afcb-b9adaff1fda8.png)

This is the fix:

```diff
diff --git a/components/Tweet.js b/components/Tweet.js
index c1fd998..4628366 100644
--- a/components/Tweet.js
+++ b/components/Tweet.js
@@ -205,7 +205,7 @@ export default function Tweet({ id, metadata, className }) {
           ))}
         </div>
       ) : null}
-      {url_meta ? (
+      {url_meta && url_meta.images && url_meta.images[0] ? (
         <a
           className="!no-underline"
           href={url_meta.unwound_url}

```

**Comment by leerob** [comment]
Hey! Happy to review + merge a PR 😄

**Comment by program247365** [comment]
@leerob  Looks like @steven-tey beat me to it!
