### ISSUE TITLE
A/B Testing with Google Optimize project does not recognize Analytics

### ISSUE THREAD

**Issue by tfcb93** [vercel/examples#57]
While trying to use [this example](https://github.com/vercel/examples/tree/main/edge-functions/ab-testing-google-optimize), and following the steps on optimize, it does not recognize my Analytics tag

![image](https://user-images.githubusercontent.com/6901304/145220013-cb522bea-b9a8-48a7-8a2d-362e9bc04152.png)
The image says that "We found problems with the Optimize installation on this page" and something like the "Google Analytics tracking code not found".

I also noticed that in the code at `components/layout.ts` there is a commented part which is
```JS
<Page>
      {/* <Script
      src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_TRACKING_ID}`}
      onLoad={() => {
        window.dataLayer = window.dataLayer || []
        function gtag() {
          dataLayer.push(arguments)
        }

        gtag('js', new Date())
        gtag('config', process.env.NEXT_PUBLIC_GOOGLE_TRACKING_ID)
      }}
    /> */}
      <Script
        src={`https://www.googleoptimize.com/optimize.js?id=${process.env.NEXT_PUBLIC_OPTIMIZE_CONTAINER_ID}`}
      />
      <GaProvider value={ga}>{children}</GaProvider>
</Page>
```
but if I uncomment it

![image](https://user-images.githubusercontent.com/6901304/145220854-10d03ed7-b16b-4b79-8714-b3d24bb66d78.png)

Errors:
- line 30: Property 'dataLayer' does not exist on type 'Window & typeof globalThis'.ts(2339)
- line 32: Cannot find name 'dataLayer'.ts(2304)
- lines 35 and 36: Expected 0 arguments, but got 2.ts(2554)

**So I wanted to know how I should include Google Analytics along with Google Optimize in this example.**

Oh, and I included both IDs on my `.env.local`

**Comment by tfcb93** [comment]
Oh yeah! I kinda did a turnaround using the [ReactGA](https://github.com/react-ga/react-ga) library. I register Analytics using it and later use `ReactGA.ga('set', 'exp', cookie);` to register the cookie set-up by the middleware.

I also did not use the script below since I was having problems getting 2 experience IDs and this can discard your experience (kinda following https://developers.google.com/optimize/devguides/experiments?technology=ga4#implement-experiment).
```JS
<Script
        src={`https://www.googleoptimize.com/optimize.js?id=${process.env.NEXT_PUBLIC_OPTIMIZE_CONTAINER_ID}`}
/>
```
It'll not recognize the installation, but seems it's not obligatory (like the server-side experiment, it's not necessary as well).
I hope you get the idea and go through it 🙏 And sorry for not updating the thread with this answer. If you need something else just post and I'll try my best to help you when I can o/

**Comment by DopamineDriven** [comment]
I do this in my repos for dealing with the datalayer. Make a Root index.d.ts, set `declaration: true` in the tsconfig, and -- 

```ts
/// <reference types="google.maps" />
/// <reference types="gtag.js" />

declare module "google.maps";
declare module "gtag.js";

interface Window {
  dataLayer?: object[];
}

```

now, the `dataLayer` will be recognized and by declaring the google.maps and gtag.js modules all of their typedefs are available for consumption globally with full Intellisense, no imports required (I only have the `@types/*` version of either installed)

**Comment by lfades** [comment]
Our Google Optimize example might disappear in the future as the service will sunset this year, closing the issue for now.
