### ISSUE TITLE
how can i hide or remove the nav and footer of the example?

### ISSUE THREAD

**Issue by alexhmyang** [vercel/examples#586]
![image](https://user-images.githubusercontent.com/10215059/223919537-a48acc54-b50c-46cf-877c-15cf0475f6ab.png)
![image](https://user-images.githubusercontent.com/10215059/223919553-5242c24e-99ed-445e-869c-f8aa202d86ea.png)

it seems i cannot edit the node modules installed by vercel after it build my github code( but I can do it locally to hide nav)

**Comment by Big-jpg** [comment]
In the `/ai-chatgpt/pages/` directory there is a TypeScript file `_app.tsx` that references the layout elements from the Vercel Examples Templates

I just repulled the repo now and rebuilt to show you these changes.

Here is the 
![built site before making the changes to the _app.tsx file](https://user-images.githubusercontent.com/56429528/226945831-02d3a336-1c50-4fe7-9890-c29c82a565ba.png)

And after changing the _app.tsx file from this:

```typescript
import type { AppProps } from 'next/app'
import { Analytics } from '@vercel/analytics/react'
import type { LayoutProps } from '@vercel/examples-ui/layout'

import { getLayout } from '@vercel/examples-ui'

import '@vercel/examples-ui/globals.css'

function App({ Component, pageProps }: AppProps) {
  const Layout = getLayout<LayoutProps>(Component)

  return (
    <Layout
      title="ai-chatgpt"
      path="solutions/ai-chatgpt"
      description="ai-chatgpt"
    >
      <Component {...pageProps} />
      <Analytics />
    </Layout>
  )
}

export default App
``` 

to this


```typescript
import type { AppProps } from 'next/app'
import { Analytics } from '@vercel/analytics/react'
import '@vercel/examples-ui/globals.css'

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Component {...pageProps} />
      <Analytics />
    </>
  );
}

export default App
``` 

![aftertest](https://user-images.githubusercontent.com/56429528/226948919-2e365e31-7722-4bed-a74a-63b9bf66b287.png)

Hope this helps! Good luck with your build and redesign :-D

**Comment by dominiksipowicz** [comment]
I believe this was answered in detail above and solved. 

Also there is one discussion around the same thing here:
https://github.com/vercel/examples/discussions/521#discussioncomment-4727248

closing.
