### ISSUE TITLE
OpenAI GPT-3 text model usage example throwing a type definition error

### ISSUE THREAD

**Issue by Big-jpg** [vercel/examples#594]
```
components\Chat.tsx (85:12) @ sendMessage

  83 | 
  84 | if (!response.ok) {
> 85 |   throw new Error(response.statusText)
     |        ^
  86 | }
  87 | 
  88 | // This data is a ReadableStream
```
  ![TypeDefError](https://user-images.githubusercontent.com/56429528/225084036-d54b469c-1d72-46e8-95e4-378e53dc3024.png)
  
Console in VSCode is throwing below warning:
`Class extends value undefined is not a constructor or null`

To replicate:

npx create-next-app --example https://github.com/vercel/examples/tree/main/solutions/ai-chatgpt

Update env.example to env.local

Input OpenAI API Key

Npm run dev

Test the message service.

I understand that this is a painful implementation and python is working seeminglyeasily enough in other projects but Vercel is too nice for NextJS to use to go learn parseltongue :-P

**Comment by Big-jpg** [comment]
Ah. I had removed some of the elements of the Payload. That was the issue. It is running fine now. 

Thanks to GPT-4 for helping me debug it though!

**Comment by songxiulin5257** [comment]
I also encountered this problem, how to solve it?

**Comment by Big-jpg** [comment]
> I also encountered this problem, how to solve it?

There are several different ways in which this error can be thrown, but I resolved it by removing all references in the Payload other than messages.
