### ISSUE TITLE
middleware is not synced with cookie

### ISSUE THREAD

**Issue by darushHamidi** [vercel/examples#597]
I have 4 routes(**Home, About, Contact, Admin**). If you want to visit the admin page first, you must have a cookie named **user**. After setting the cookie, you can not visit the admin page,
you have to reload the page to be able to
visit it.

I set the **user** cookie like the following:

```
import { getCookies, setCookie, deleteCookie, hasCookie } from 'cookies-next';
import { useRouter } from 'next/router';

export default function LoginPage() {

    const router = useRouter()

    const login = () => {
        if (hasCookie('user')) {
            router.push('/');
            return;
        }

        setCookie('user', 'DHamidi-RandomValue')
        router.push('/');
    }

    return <div className="layout">
        <h2>Login</h2>

        <button onClick={login}>
            Add User Info To Cookie.
        </button>
    </div>
}

```
In the middleware, I check whether the cookie exists or not, if exists, you can visit the admin page otherwise you redirect to the login page

```
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// This function can be marked `async` if using `await` inside
export function middleware(request: NextRequest) {
    if (request.cookies.get('user')?.value) return NextResponse.next()
    
    return NextResponse.redirect(new URL('/login', request.url))
}

export const config = {
    matcher: '/admin/:path*',
}
```

Why do I have to reload the page after login?

It works in development mode perfectly (npm run dev).but the problem happens in production mode(npm run build => npm run start).

If you want to see the problem in action, Please clone [this simple project](https://github.com/darushHamidi/next-middleware)

**Comment by leerob** [comment]
Hey there, we can't provide support for a third-party package `cookies-next`.

Here's some details on setting cookies with the App Router https://nextjs.org/docs/app#how-can-i-set-cookies.
