### ISSUE TITLE
Amazon S3 example needs to be updated. 

### ISSUE THREAD

**Issue by kdesimini** [vercel/examples#609]
https://github.com/vercel/examples/tree/main/solutions/aws-s3-image-upload no longer a valid guide to bootstrapping as the AWS console has changed. Steps are confusing as well. Where do we perform step 5?

**Comment by leerob** [comment]
What specifically do you see that's changed?

**Comment by christopher-ha** [comment]
Hi, I used a variation of this example in my project for Next 13.2.4 using the new API routes handlers and have a current working solution using presignedPost URLs similar to the example, but I need help submitting a solution to open source.

@leerob How can I share this with others?

**Comment by davidlinc1** [comment]
FYI @leerob @christopher-ha - after the update, deploying from Vercel's demo page sets you up with the wrong env vars.

Noodled with this a bit, found out both `BUCKET_NAME` and `REGION` now need `AWS_` prefixed (which is already correctly changed in the repo's `.env.example`.

Sorry for not fixing with a PR, if I knew offhand how/where to do so, I would!

**Comment by leerob** [comment]
Thanks! Fixed.
