### ISSUE TITLE
Update basic auth example to store to cookies

### ISSUE THREAD

**Issue by leerob** [vercel/examples#62]
Nice idea here https://gist.github.com/mtt87/cb9f36665165112468b92aa9fb470c7e

**Comment by DevCleverton** [comment]
Hello, dear! managed to solve? comment there close as resolved if yes 🎉✨

**Comment by dominiksipowicz** [comment]
The gist combines cookies and basic authentication. If we want to keep things simple, I wouldn't combine the two options into one example, but maybe create a separate one like "cookie-based-access"
