### ISSUE TITLE
Basic Auth Password for Next 13 /App

### ISSUE THREAD

**Issue by thefubon** [vercel/examples#640]
https://github.com/vercel/examples/tree/main/edge-middleware/basic-auth-password

Please tell me how to do the same for Next 13 with the Excelmental /App

**Comment by emilwalter** [comment]
Not sure if you ever figured it out, but this works for the route handlers:

`export async function GET(request: Request) {
  return new Response("Auth Required.", {
    status: 401,
    headers: { "WWW-authenticate": `Basic realm="Secure Area` },
  });
}
`

**Comment by leerob** [comment]
^ Thanks for providing that!
