### ISSUE TITLE
`next-intl` example for Vercel Templates?

### ISSUE THREAD

**Issue by amannn** [vercel/examples#694]
Hello! 👋

I noticed that you're hosting a [list of templates on the Vercel website](https://vercel.com/templates), many of them based on Next.js.

I'm the maintainer of [`next-intl`](https://next-intl-docs.vercel.app/), an internationalization solution for Next.js. I was wondering if you're interested in hosting an i18n example based on `next-intl` there? Maybe some users could be interested when searching for keywords like "i18n" and "internationalization"?

[Template repository](https://github.com/amannn/next-intl/tree/main/examples/example-next-13)
[Demo deployment](https://next-intl-example-next-13.vercel.app/)

Let me know if I can help!

**Comment by leerob** [comment]
Hey! We have y'all listed here https://nextjs.org/docs/app/building-your-application/routing/internationalization#resources
