### ISSUE TITLE
serverless nodejs example is not working

### ISSUE THREAD

**Issue by KMJ-007** [vercel/examples#767]
i tried the nodejs serverless example, deployed it, i tried on my device also using vercel dev, but it is giving me 404

https://github.com/vercel/examples/tree/main/solutions/node-hello-world

it would be great help if anyone can guide me what i am doing wrong or is there anything wrong with given example

**Comment by leerob** [comment]
Confirmed this is working here: https://nodejs-api-example.vercel.app/api/hello

https://vercel.com/templates/other/nodejs-serverless-function-express

Could you share more?
