### ISSUE TITLE
Web3 Authentication example is insecure

### ISSUE THREAD

**Issue by mlewandowskim** [vercel/examples#828]
Hi,

I believe that the solution provided in [this example](https://github.com/vercel/examples/tree/main//solutions/web3-sessions) is extremely insecure. ***Anybody can inject their own "metamask" object into the browser*** and thus authenticate as someone else.
I know you guys work hard and I appreciate your effort to in making this amazing framework. 
However, if anyone had built an application based on this example it would be a disaster as the crypto community is extremely tech-savvy and can spot such vulnerabilities very quickly.

Cheers.

**Comment by manovotny** [comment]
@mlewandowskim thanks for raising the concern. The example wasn't ours to begin with and hasn't seen updates for a while, so we decided to remove it instead.
