### ISSUE TITLE
nextjs-flask: The flask api endpoint is not working.

### ISSUE THREAD

**Issue by AbubakrChan** [vercel/examples#841]
Seeing the index.py code in api in the nextjs-flask starter, this url https://nextjs-flask-starter.vercel.app/api/python should have return the 'Hello World'.

Code:
`from flask import Flask
app = Flask(__name__)

@app.route("/api/python")
def hello_world():
    return "<p>Hello, World!</p>"`
    
Insteadit returns : 500 Internal Server Error.

Thank you!

**Comment by Demiduska** [comment]
Hi, I have the same problem, after adding to requirements.txt it will start to work:

`numpy==1.24.3
Flask==2.2.2
Werkzeug>=2.0.0,<3.0.0`

**Comment by AbubakrChan** [comment]
Thanks, running it locally worked for me.
