### ISSUE TITLE
Node.js Serverless Function template doesn't work (gives a 404)

### ISSUE THREAD

**Issue by janek** [vercel/examples#852]
This is a duplicate of #767. It's about https://vercel.com/templates/other/nodejs-serverless-function-express.

- Vercel's online demo works (https://nodejs-api-example.vercel.app/api/hello)
- One-click deploy doesn't work (404)
- Local development doesn't work (404)

**Reproduction - deploy**
1. Click deploy on https://vercel.com/templates/other/nodejs-serverless-function-express
2. Go through the process, i.e. authorize creating a repository
3. Go to your deployment 
4. You will see a 404

**Reproduction - local**
1. Clone/copy the template locally
2. `vercel dev`
3. Go to `localhost:3000` 
4. You will see a 404

<img width="533" alt="image" src="https://github.com/vercel/examples/assets/2146927/698c1660-049f-408d-8227-77dab3ab3901">

**Comment by leerob** [comment]
You need to go to the route: `/api/hello`.

e.g. https://nodejs-api-example.vercel.app/api/hello

**Comment by janek** [comment]
Right! Thanks and sorry for the confusion.
