### ISSUE TITLE
aws-s3-image upload example

### ISSUE THREAD

**Issue by yashsharma999** [vercel/examples#971]
I think something is missing in the example, 

i get the following response 
```
<Error
>
<Code
>
AccessDenied
</Code
>
<Message
>
User: arn:aws:iam::271583835787:user/yash-google is not authorized to perform: s3:CreateBucket on resource: "arn:aws:s3:::google-lens-1" because public access control lists (ACLs) are blocked by the BlockPublicAcls block public access setting.
</Message
>
<RequestId
>
R6J5ZEN5E78X269N
</RequestId
>
<HostId
>
zwrGbeNQqKK2/HuKa/dxOq1z5uaSAjda+F3UEk3Rxzlsu4A6WeA1RHRSjz0tySnlaJdUcVGd9St3hxeWbVAMVGqFW0w0UEViksGKAAOzHI4=
</HostId
>
</Error>
```

**Comment by developerjhp** [comment]
It seems like the error might be related to the "Block Public Access" settings for your S3 bucket. Could you please check the following?

1. Navigate to your S3 bucket in the AWS Management Console.
2. Go to the **Permissions** tab.
3. Under **Block public access (bucket settings)**, make sure to uncheck **"Block all public access"**.

If this doesn't resolve the issue, could you let me know your exact S3 bucket configuration and whether you're using the provided IAM policy from the README? I'd be happy to help troubleshoot further! 😊

**Comment by yashsharma999** [comment]
I actually managed to resolve the issue already, following the same steps you suggested.
